export const USER_INITIATED = "USER_INITIATED";
export const USER_AUTHENTICATION_INITIATED = "USER_AUTHENTICATION_INITIATED";
export const USER_AUTHENTICATION_SUCCESS = "USER_AUTHENTICATION_SUCCESS";
export const USER_AUTHENTICATION_FAILED = "USER_AUTHENTICATION_FAILED";
export const USER_UPDATE = "USER_UPDATE";
export const USER_LOGOUT = "USER_LOGOUT";
