export const INITIAL_SIDEBAR_STATE = "INITIAL_SIDEBAR_STATE";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_SIDEBAR = "LOGOUT_SIDEBAR";
export const TOGGLE_SIDEBAR_CLOSE = "TOGGLE_SIDEBAR_CLOSE";
