export const TIMEZONE_INITIATED = "TIMEZONE_INITIATED";
export const TIMEZONE_SUCCESS = "TIMEZONE_SUCCESS";
export const TIMEZONE_FAILED = "TIMEZONE_FAILED";
export const TIMEZONE_LOGOUT = "TIMEZONE_LOGOUT";
