export const COPARENTS_INITIATED = "COPARENTS_INITIATED";
export const COPARENTS_FAILED = "COPARENTS_FAILED";
export const COPARENTS_SUCCESS = "COPARENTS_SUCCESS";
export const COPARENTS_LOGOUT = "COPARENTS_LOGOUT";
