export const NOTIFICATION_INITIATED = "NOTIFICATION_INITIATED";
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_FAILED = "NOTIFICATION_FAILED";
export const NOTIFICATION_DELETE_FEED = "NOTIFICATION_DELETE_FEED";

export const NOTIFICATION_ATLAUNCH_TOGGLE = "NOTIFICATION_ATLAUNCH_TOGGLE";
export const NOTIFICATION_ATLAUNCH_INITIATED =
  "NOTIFICATION_ATLAUNCH_INITIATED";
export const NOTIFICATION_ATLAUNCH_SUCCESS = "NOTIFICATION_ATLAUNCH_SUCCESS";
export const NOTIFICATION_ATLAUNCH_FAILED = "NOTIFICATION_ATLAUNCH_FAILED";
export const NOTIFICATION_LOGOUT = "NOTIFICATION_LOGOUT";
